const MEDIA = [
  {
    id: '1',
    artist: 'Nirvana',
    title: 'Come As You Are',
    track: 'nirvana-comeasyouare.mp3',
    thumbnail: 'nirvana1-100px.jpg',
    large: 'nirvana1.jpeg',
    time: '',
  },
  {
    id: '2',
    artist: 'Beck',
    title: 'Loser',
    track: 'beck-loser.mp3',
    thumbnail: 'beck100px.jpg',
    large: 'beck.jpeg',
    time: '',
  },
  {
    id: '3',
    artist: 'Nirvana',
    title: 'Heart Shaped Box',
    track: 'nirvana-heartshapedbox.mp3',
    thumbnail: 'nirvana2-100px.jpg',
    large: 'nirvana2.jpeg',
    time: '',
  },
  {
    id: '4',
    artist: 'Red Hot Chillie Peppers',
    title: 'Scar Tissue',
    track: 'rhcp-scartissue.mp3',
    thumbnail: 'scartissue100px.jpg',
    large: 'scartissue.jpeg',
    time: '',
  },
  {
    id: '5',
    artist: 'Radio Head',
    title: 'Creep',
    track: 'radiohead-creep.mp3',
    thumbnail: 'radioHead100px.jpg',
    large: 'radiohead.jpeg',
    time: '',
  },
  {
    id: '6',
    artist: 'Sound Garden',
    title: 'Black Hole Sun',
    track: 'soundgarden-blackholesun.mp3',
    thumbnail: 'soundgarden100px.jpg',
    large: 'soundgarden.jpeg',
    time: '',
  },
  {
    id: '7',
    artist: 'Nirvana',
    title: 'Smells Like Teen Spirit',
    track: 'nirvana-smellsliketeenspirit.mp3',
    thumbnail: 'nirvana1-100px.jpg',
    large: 'nirvana1.jpeg',
    time: '',
  },
];
export default MEDIA;