const MEDIA = [
  {
    id: '1',
    artist: 'Nirvana',
    title: 'Come As You Are',
    track : './media/nirvana-comeasyouare.mp3',
    thumbnail: './img/nirvana1-100px.jpg',
    large: './img/nirvana1.jpeg',
    time: '3:44',
  },
  {
    id: '2',
    artist: 'Beck',
    title: 'Loser',
    track: './media/beck-loser.mp3',
    thumbnail: './img/beck100px.jpg',
    large: './img/beck.jpeg',
    time: '3:52',
  },
  {
    id: '3',
    artist: 'Nirvana',
    title: 'Heart Shaped Box',
    track: './media/nirvana-heartshapedbox.mp3',
    thumbnail: './img/nirvana2-100px.jpg',
    large: './img/nirvana2.jpeg',
    time: '4:43',
  },
  {
    id: '4',
    artist: 'Red Hot Chillie Peppers',
    title: 'Scar Tissue',
    track: './media/rhcp-scartissue.mp3',
    thumbnail: './img/scartissue100px.jpg',
    large: './img/scartissue.jpeg',
    time: '3:41',
  },
  {
    id: '5',
    artist: 'Radio Head',
    title: 'Creep',
    track: './media/radiohead-creep.mp3',
    thumbnail: './img/radiohead100px.jpg',
    large: './img/radiohead.jpeg',
    time: '3:57',
  },
  {
    id: '6',
    artist: 'Sound Garden',
    title: 'Black Hole Sun',
    track: './media/soundgarden-blackholesun.mp3',
    thumbnail: './img/soundgarden100px.jpg',
    large: './img/soundsgarden.jpeg',
    time: '5:20',
  },
  {
    id: '7',
    artist: 'Nirvana',
    title: 'Smells Like Teen Spirit',
    track: './media/nirvana-smellsliketeenspirit.mp3',
    thumbnail: './img/nirvana1-100px.jpg',
    large: './img/nirvana1-jpeg',
    time: '4:38',
  },
];
export default MEDIA;